package com.hotmail.or_dvir.tack.models

import com.hotmail.or_dvir.tack.elapsedTimeUserFriendly

data class SleepWakeWindowModel(
    val startMillis: Long,
    val endMillis: Long,
    val sleepWake: SleepWake,
    // generated by room
    val id: Int = 0
) {
    val durationMillis = endMillis - startMillis
    val elapsedTimeUserFriendly = elapsedTimeUserFriendly(startMillis, endMillis)
}
