package com.hotmail.or_dvir.tack.models

data class SleepWakeWindowModel(
    val startMillis: Long,
    val endMillis: Long,
    val sleepWake: SleepWake,
    // generated by room
    val id: Int = 0,
) {
    val totalTimeMillis = endMillis - startMillis
}
