package com.hotmail.or_dvir.tack.models

import com.hotmail.or_dvir.tack.SINGLE_DIGIT_LIMIT
import com.hotmail.or_dvir.tack.timeElapsed

data class SleepWakeWindowModel(
    val startMillis: Long,
    val endMillis: Long,
    val sleepWake: SleepWake,
    // generated by room
    val id: Int = 0,
) {
    val duration = endMillis - startMillis

    val elapsedTimeUserFriendly: String
        get() {
            val elapsed = timeElapsed(startMillis, endMillis)

            val hours = elapsed.first.let { hrs ->
                hrs.takeUnless { it < SINGLE_DIGIT_LIMIT }?.toString() ?: "0$hrs"
            }

            val minutes = elapsed.second.let { min ->
                min.takeUnless { it < SINGLE_DIGIT_LIMIT }?.toString() ?: "0$min"
            }
            val seconds = elapsed.third.let { sec ->
                sec.takeUnless { it < SINGLE_DIGIT_LIMIT }?.toString() ?: "0$sec"
            }

            return "$hours:$minutes:$seconds"
        }
}
